const QUESTIONS = {
  ciencias: = [
  // ETAPA 1 (Imunidade/Vacinas) - 37 questões
  {id:1, s:1, d:'f', q:"Anticorpos são:", alt:["Proteínas de defesa","Vírus enfraquecidos","Bactérias boas","Minerais essenciais"], c:0, e:"Anticorpos são proteínas do sistema imune que combatem invasores."},
  {id:2, s:1, d:'f', q:"A vacina serve para:", alt:["Tratar doenças agudas","Prevenir doenças","Substituir antibióticos","Curar ferimentos"], c:1, e:"Vacinas são preventivas. Estimulam a memória imunológica."},
  {id:3, s:1, d:'f', q:"O soro terapêutico contém:", alt:["Anticorpos prontos","Vírus vivos","Antibióticos","Hormônios"], c:0, e:"Soros possuem anticorpos prontos para ação rápida e imediata."},
  {id:4, s:1, d:'f', q:"Aumento rápido de casos em uma região define:", alt:["Pandemia","Endemia","Epidemia","Imunidade"], c:2, e:"Epidemia = surto localizado e repentino."},
  {id:5, s:1, d:'f', q:"Doença constante em uma região é:", alt:["Endemia","Epidemia","Pandemia","Vacinação"], c:0, e:"Endemia = presença contínua e esperada na área."},
  {id:6, s:1, d:'f', q:"PANdemia refere-se a:", alt:["Região específica","Mundo inteiro","Apenas animais","Clima quente"], c:1, e:"PAN = todos. Doença espalhada globalmente."},
  {id:7, s:1, d:'m', q:"Qual afirmação sobre vacinas é VERDADEIRA?", alt:["Causam a doença","Substituem a higiene","Protegem apenas o indivíduo","Reduzem a circulação do patógeno"], c:3, e:"A vacinação em massa cria imunidade de rebanho e freia a transmissão."},
  {id:8, s:1, d:'m', q:"Uma pessoa picada por cobra deve usar:", alt:["Vacina antiofídica","Soro antiofídico","Antibiótico","Anti-inflamatório"], c:1, e:"Soro, pois a ação precisa ser imediata contra a peçonha já no corpo."},
  {id:9, s:1, d:'m', q:"Fake news em saúde geralmente NÃO apresenta:", alt:["Medo","Curas milagrosas","Fontes científicas","Emojis"], c:2, e:"Notícias falsas carecem de respaldo científico e fontes confiáveis."},
  {id:10, s:1, d:'m', q:"A imunidade adquirida naturalmente após doença vs vacina:", alt:["Vacina é mais arriscada","Vacina gera resposta mais segura e controlada","Natural é sempre melhor","São idênticas"], c:1, e:"Vacinas simulam a infecção sem os riscos da doença real."},
  {id:11, s:1, d:'m', q:"Antibióticos NÃO funcionam contra:", alt:["Bactérias","Vírus","Protozoários","Fungos"], c:1, e:"Antibióticos atacam estruturas bacterianas. Vírus não têm essas estruturas."},
  {id:12, s:1, d:'m', q:"O SUS oferece vacinas porque:", alt:["É obrigação constitucional","Gera lucro","É teste clínico","Substitui médicos"], c:0, e:"Direito à saúde e prevenção coletiva no Brasil."},
  {id:13, s:1, d:'m', q:"Se uma mensagem diz que 'vacina altera DNA', é provável:", alt:["Fato científico","Fake news","Novidade médica","Consenso"], c:1, e:"Vacinas de RNA/DNA atuam no citoplasma, não alteram genoma humano."},
  {id:14, s:1, d:'m', q:"A expressão 'post hoc ergo propter hoc' alerta para:", alt:["Efeito vacinal","Correlação não implica causalidade","Mutação viral","Prevenção"], c:1, e:"Falácia lógica: 'depois disso, logo causado por isso'."},
  {id:15, s:1, d:'d', q:"Por que a vacina da gripe muda todo ano?", alt:["Bactérias resistem","Vírus da gripe sofre mutações frequentes","SUS quer vender mais","Perde validade no calor"], c:1, e:"Alta taxa de mutação (drift antigênico) exige atualização anual."},
  {id:16, s:1, d:'d', q:"Imunidade de rebanho ocorre quando:", alt:["Todos tomam soro","Maioria está imune, protegendo os vulneráveis","Animais são vacinados","Doença some sozinha"], c:1, e:"Barreira epidemiológica que impede a circulação ativa."},
  {id:17, s:1, d:'d', q:"Em um ensaio clínico, o grupo controle recebe:", alt:["Vacina experimental","Placebo/Soro fisiológico","Nada","Antibiótico"], c:1, e:"Para comparar efeitos reais vs psicológicos/naturais."},
  {id:18, s:1, d:'d', q:"O soro antitetânico é aplicado quando:", alt:["Há ferimento sujo/profundo","Antes da ferida","Na gripe","No cólera"], c:0, e:"Prevenção pós-exposição imediata ao bacilo do tétano."},
  {id:19, s:1, d:'f', q:"A poliomielite pode causar:", alt:["Manchas vermelhas","Paralisia infantil","Diarreia","Tosse seca"], c:1, e:"Vírus ataca nervos motores, podendo paralisar membros."},
  {id:20, s:1, d:'f', q:"O sarampo é prevenido pela vacina:", alt:["BCG","Tríplice viral","Pentavalente","HPV"], c:1, e:"Protege contra Sarampo, Caxumba e Rubéola."},
  {id:21, s:1, d:'m', q:"A rubéola é perigosa principalmente para:", alt:["Idosos","Crianças pequenas","Gestantes","Homens"], c:2, e:"Pode atravessar a placenta e causar malformações fetais."},
  {id:22, s:1, d:'m', q:"A caxumba pode causar esterilidade em:", alt:["Crianças","Adolescentes/Adultos","Idosos","Animais"], c:1, e:"Inflamação dos testículos/ovários em pós-puberdade."},
  {id:23, s:1, d:'m', q:"A varíola foi erradicada graças a:", alt:["Antibióticos","Vacinação em massa","Isolamento total","Higiene"], c:1, e:"Única doença humana erradicada por campanhas globais."},
  {id:24, s:1, d:'m', q:"Qual vitamina NÃO previne doenças virais diretamente?", alt:["A","C","D","Todas são curas milagrosas"], c:3, e:"Vitaminas apoiam imunidade, mas não substituem vacinas/tratamento."},
  {id:25, s:1, d:'m', q:"A raiva também é conhecida como:", alt:["Hidrofobia","Febre alta","Catapora","Maleita"], c:0, e:"Medo de água devido a espasmos na deglutição."},
  {id:26, s:1, d:'m', q:"Animais vacinados contra raiva:", alt:["Transmitem mais","Não espalham o vírus","Ficam agressivos","Devem ser soltos"], c:1, e:"Quebram o ciclo de transmissão entre animais e humanos."},
  {id:27, s:1, d:'m', q:"Se você tocar em um animal suspeito de raiva:", alt:["Esperar sintomas","Lavar com água e sabão e ir ao posto","Tomar chá","Ignorar"], c:1, e:"Higiene imediata + avaliação médica para soro/vacina."},
  {id:28, s:1, d:'m', q:"O vírus da raiva afeta principalmente:", alt:["Intestino","Pulmão","Sistema nervoso","Pele"], c:2, e:"Migra pelos nervos até o cérebro, causando danos graves."},
  {id:29, s:1, d:'m', q:"A vacinação obrigatória em 1904 gerou:", alt:["Revolta da Vacina","Comemoração","Nada","Protesto ambiental"], c:0, e:"Conflito histórico no Rio de Janeiro por falta de informação."},
  {id:30, s:1, d:'m', q:"Edward Jenner criou a primeira vacina usando:", alt:["Cachorro","Gato","Varíola bovina","Planta"], c:2, e:"Vaccina (varíola da vaca) protegeu contra a humana."},
  {id:31, s:1, d:'d', q:"A eficácia da vacina NÃO significa:", alt:["100% de proteção individual","Redução de casos graves","Controle populacional","Imunização duradoura"], c:0, e:"Nenhuma é 100%, mas reduzem drasticamente gravidade/transmissão."},
  {id:32, s:1, d:'d', q:"Para que uma vacina seja aprovada, ela passa por:", alt:["Testes em animais, humanos e fase 3", "Apenas opinião de médicos", "Venda direta", "Teste em 1 pessoa"], c:0, e:"Fases rigorosas de segurança, dosagem e eficácia."},
  {id:33, s:1, d:'d', q:"O termo 'antígeno' refere-se a:", alt:["Defesa do corpo","Substância que desencadeia resposta imune","Remédio","Anticorpo pronto"], c:1, e:"Parte do patógeno que o sistema imune reconhece como estranho."},
  {id:34, s:1, d:'d', q:"A memória imunológica permite que:", alt:["Fiquemos doentes sempre","O corpo reaja mais rápido na 2ª exposição","Precisemos de soro toda vez","Anticorpos sumam"], c:1, e:"Células de memória aceleram produção de anticorpos."},
  {id:35, s:1, d:'d', q:"Qual NÃO é vetor biológico?", alt:["Mosquito","Carrapato","Barbeiro","Seringa"], c:3, e:"Seringa é veículo/fomito, não vetor biológico vivo."},
  {id:36, s:1, d:'d', q:"A transmissão vertical ocorre:", alt:["Pai para filho","Mãe para feto/bebê","Animal para humano","Água para pessoa"], c:1, e:"Durante gestação, parto ou amamentação."},
  {id:37, s:1, d:'d', q:"A 'imunidade coletiva' protege:", alt:["Apenas vacinados","Vacinados e não vacinados vulneráveis","Somente médicos","Ninguém"], c:1, e:"Reduz circulação, protegendo imunodeprimidos e alérgicos."},
  
  // ETAPA 2 (Doenças Virais) - 40 questões
  {id:38, s:2, d:'f', q:"O SARS-CoV-2 causa:", alt:["Gripe","Covid-19","Dengue","Tétano"], c:1, e:"Vírus da família coronavírus responsável pela pandemia recente."},
  {id:39, s:2, d:'f', q:"A dengue é transmitida por:", alt:["Água suja","Mosquito Aedes","Contato físico","Ar"], c:1, e:"Vetor urbano Aedes aegypti (e albopictus)."},
  {id:40, s:2, d:'f', q:"Zika pode causar no feto:", alt:["Paralisia","Microcefalia","Diabetes","Cegueira"], c:1, e:"Compromete desenvolvimento cerebral intrauterino."},
  {id:41, s:2, d:'f', q:"Chikungunya tem sintoma forte de:", alt:["Tosse","Dores articulares","Diarreia","Manchas roxas"], c:1, e:"Dores intensas e prolongadas nas juntas."},
  {id:42, s:2, d:'f', q:"Febre amarela urbana no Brasil:", alt:["É comum","Foi erradicada (último caso 1942)", "Só existe no Nordeste","É leve"], c:1, e:"Controlada por vacinação e combate ao vetor. Silvestre ainda circula."},
  {id:43, s:2, d:'f', q:"Macacos na febre amarela são:", alt:["Culpados","Vítimas/sentinelas","Vetores","Imunes"], c:1, e:"Morrem com a doença. Sua morte alerta para circulação viral."},
  {id:44, s:2, d:'m', q:"A covid-19 se espalha principalmente por:", alt:["Apenas contato","Gotículas e aerossóis","Comida crua","Mosquitos"], c:1, e:"Respiração próxima e ambientes fechados facilitam aerossóis."},
  {id:45, s:2, d:'m', q:"Para reduzir transmissão da covid, usa-se:", alt:["Máscara + distância + ventilação","Só álcool","Só vacina","Isolamento total"], c:0, e:"Combinação de medidas (queijo suíço) é mais eficaz."},
  {id:46, s:2, d:'m', q:"O teste PCR detecta:", alt:["Anticorpos","Material genético do vírus","Células brancas","Bactérias"], c:1, e:"Amplifica RNA viral para diagnóstico agudo."},
  {id:47, s:2, d:'m', q:"Sorologia na covid detecta:", alt:["Vírus vivo","Resposta imunológica (anticorpos)","Sintomas","RNA"], c:1, e:"Indica infecção passada ou vacinação."},
  {id:48, s:2, d:'m', q:"O lockdown visa:", alt:["Aumentar turismo","Evitar colapso da saúde","Fechar escolas para sempre","Substituir vacinas"], c:1, e:"Reduzir velocidade de transmissão para proteger hospitais."},
  {id:49, s:2, d:'m', q:"Aedes aegypti se reproduz em:", alt:["Água corrente","Água parada limpa ou suja","Só em lixo","Só em rios"], c:1, e:"Qualquer recipiente com água parada é foco."},
  {id:50, s:2, d:'m', q:"Ciclo do Aedes leva cerca de:", alt:["1 mês","10 dias (favorável)","1 ano","2 dias"], c:1, e:"Rápido, por isso eliminação semanal de água parada."},
  {id:51, s:2, d:'m', q:"Dengue hemorrágica ocorre mais em:", alt:["1ª infecção","2ª infecção por sorotipo diferente","Quem toma vacina","Crianças só"], c:1, e:"Anticorpos não neutralizantes facilitam infecção grave."},
  {id:52, s:2, d:'m', q:"Sintoma de alarme na dengue:", alt:["Só coceira","Dor abdominal, sangramento, letargia","Manchas leves","Tosse"], c:1, e:"Indica extravasamento plasmático e choque."},
  {id:53, s:2, d:'m', q:"Febre amarela silvestre é transmitida por:", alt:["Aedes","Haemagogus/Sabethes","Barbeiro","Pulga"], c:1, e:"Mosquitos de mata. Humanos infectados podem reintroduzir na cidade."},
  {id:54, s:2, d:'m', q:"Zika é transmitida também por:", alt:["Beijo","Relação sexual e transfusão","Ar condicionado","Picada de cobra"], c:1, e:"Vírus permanece no sêmen por meses."},
  {id:55, s:2, d:'m', q:"A poliomielite é transmitida via:", alt:["Ar","Fecal-oral (água/alimentos)","Mosquito","Sangue"], c:1, e:"Vírus eliminado nas fezes contamina ambiente."},
  {id:56, s:2, d:'m', q:"A caxumba ataca:", alt:["Rins","Glândulas salivares (parótida)","Fígado","Coração"], c:1, e:"Inchaço característico na região das orelhas."},
  {id:57, s:2, d:'m', q:"Catapora deixa:", alt:["Cicatrizes se coçadas","Manchas permanentes","Paralisia","Esterilidade"], c:0, e:"Bolhas coçam. Coçar pode causar infecção bacteriana secundária."},
  {id:58, s:2, d:'m', q:"Gripe vs Resfriado:", alt:["São iguais","Gripe tem febre alta/dores; resfriado leve","Resfriado é viral, gripe bacteriana","Gripe não tem vacina"], c:1, e:"Influenza (gripe) é mais sistêmico e grave."},
  {id:59, s:2, d:'m', q:"A raiva em humanos é quase sempre:", alt:["Curável com remédio caseiro","Fatal se não tratada cedo","Leve","Autoimune"], c:1, e:"Quando sintomas neurológicos aparecem, letalidade é ~100%."},
  {id:60, s:2, d:'m', q:"Qual NÃO é virose?", alt:["Sarampo","Tétano","Hepatite A","HPV"], c:1, e:"Tétano é bacteriano (Clostridium tetani)."},
  {id:61, s:2, d:'d', q:"Aedes albopictus:", alt:["Não transmite dengue","Pode transmitir, vive em matas/periferias","É menor que aegypti","Só bebe água doce"], c:1, e:"Vetor secundário importante, adaptado a diferentes climas."},
  {id:62, s:2, d:'d', q:"A vacina da febre amarela:", alt:["Precisa de reforço anual","É dose única vitalícia","Causa febre em 100%","Não protege"], c:1, e:"Uma dose confere imunidade duradoura."},
  {id:63, s:2, d:'d', q:"Chikungunya pode causar:", alt:["Morte em 24h","Artrite crônica","Paralisia","Cegueira"], c:1, e:"Dores articulares podem persistir por anos."},
  {id:64, s:2, d:'d', q:"Pneumonia viral vs bacteriana:", alt:["Sempre tratada com antibiótico","Viral não responde a antibióticos","São iguais","Viral só dá em idosos"], c:1, e:"Uso inadequado de antibióticos em viroses gera resistência."},
  {id:65, s:2, d:'d', q:"A transmissão da covid por superfícies é:", alt:["Principal via","Rara/possível","Impossível","Só por metal"], c:1, e:"Via secundária. Aerossóis e gotículas são dominantes."},
  {id:66, s:2, d:'d', q:"O vírus da gripe é classificado por:", alt:["Tamanho","Hemaglutinina/Neuraminidase (H/N)","Cor","País de origem"], c:1, e:"Ex: H1N1. Define subtipos e vacinas."},
  {id:67, s:2, d:'d', q:"Aedes aegypti tem hábitos:", alt:["Noturnos","Preferencialmente diurnos (amanhecer/entardecer)","Apenas à noite","Só em florestas"], c:1, e:"Pode picar à noite, mas pico é diurno."},
  {id:68, s:2, d:'d', q:"HPV está associado a:", alt:["Gripe","Câncer de colo do útero/pênis","Dengue","Tétano"], c:1, e:"Papilomavírus humano. Vacina previne verrugas e câncer."},
  {id:69, s:2, d:'d', q:"A varicela (catapora) no adulto pode virar:", alt:["Caxumba","Herpes zóster","Gripe","Febre"], c:1, e:"Vírus fica latente nos nervos e reativa anos depois."},
  {id:70, s:2, d:'d', q:"Sarampo é altamente contagioso porque:", alt:["Só pega com toque","Vírus fica no ar por até 2h","Só pega com sangue","Só em escolas"], c:1, e:"R0 muito alto. Suscetíveis não vacinados quase sempre pegam."},
  {id:71, s:2, d:'f', q:"Qual doença causa 'hidrofobia'?", alt:["Cólera","Raiva","Dengue","Malária"], c:1, e:"Medo de água/espasmo na garganta."},
  {id:72, s:2, d:'f', q:"O que é 'aerossol' na transmissão viral?", alt:["Gota grande","Partículas minas que ficam suspensas no ar","Poeira","Água parada"], c:1, e:"Permanece no ar, risco em ambientes fechados."},
  {id:73, s:2, d:'f', q:"Febre amarela urbana depende de:", alt:["Aedes","Barbeiro","Caramujo","Pulga"], c:0, e:"Retorno à cidade via humano infectado + Aedes."},
  {id:74, s:2, d:'m', q:"A poliomielite NÃO causa:", alt:["Febre","Paralisia","Diarreia intensa constante","Esterilidade"], c:3, e:"Atinge SNC/músculos, não órgãos reprodutivos."},
  {id:75, s:2, d:'m', q:"Zika vírus pode ser detectado por:", alt:["PCR/Exame clínico/ Sorologia","Só raio-X","Só exame de fezes","Apenas palpação"], c:0, e:"Diagnóstico clínico + laboratorial."},
  {id:76, s:2, d:'m', q:"Dengue, Zika e Chikungunya compartilham:", alt:["Mesmo vírus","Mesmo vetor principal","Mesmo tratamento específico","Só atingem crianças"], c:1, e:"Transmitidas pelo mesmo mosquito, exigem controle integrado."},
  {id:77, s:2, d:'m', q:"A vacina tríplice viral protege contra:", alt:["Sarampo, Caxumba, Rubéola","Gripe, Dengue, Zika","Tétano, Difteria, Coqueluche","HPV, Hep B, A"], c:0, e:"Calendário infantil básico."},
  {id:78, s:2, d:'m', q:"A transmissão da poliomielite pode ser evitada com:", alt:["Saneamento e vacinação","Só antibiótico","Isolamento total","Comer carne"], c:0, e:"Vacina OPV/IPV + água/esgoto tratada."},
  {id:79, s:2, d:'m', q:"Qual sintoma é TÍPICO da caxumba?", alt:["Inchaço nas parótidas","Manchas vermelhas","Tosse com sangue","Dor abdominal"], c:0, e:"Parotidite: glândulas salivares inflamadas."},
  {id:80, s:2, d:'d', q:"A febre amarela ataca principalmente o:", alt:["Fígado","Pulmão","Coração","Rim"], c:0, e:"Icterícia, hemorragias, lesão hepática."},
  {id:81, s:2, d:'d', q:"Aedes aegypti é resistente a:", alt:["Água fria","Muitos inseticidas tradicionais (desenvolve resistência)","Sol forte","Sabão"], c:1, e:"Pressão seletiva exige rotação de ativos e controle mecânico."},
  {id:82, s:2, d:'d', q:"O vírus da gripe sofre 'drift' e 'shift'. Isso significa:", alt:["Fica igual","Muda gradualmente ou por recombinação súbita","Morre rápido","Só muda no inverno"], c:1, e:"Motivo das pandemias (shift) e vacinas anuais (drift)."},
  {id:83, s:2, d:'d', q:"A rubéola é perigosa para gestantes porque causa:", alt:["Síndrome da rubéola congênita","Aborto espontâneo só","Náusea","Dor nas costas"], c:0, e:"Surdez, catarata, cardiopatia no feto."},
  {id:84, s:2, d:'d', q:"A dengue NÃO se transmite por:", alt:["Picada de Aedes","Contato direto com doente (tosse/beijo)","Transfusão","Transplante de órgãos"], c:1, e:"Vírus não circula no ar/saliva para infecção direta."},
  {id:85, s:2, d:'d', q:"O tratamento da dengue foca em:", alt:["Antibiótico forte","Hidratação e repouso","Quimioterapia","Cirurgia"], c:1, e:"Evitar desidratação e choque. NÃO usar AAS/anti-inflamatórios."},
  {id:86, s:2, d:'d', q:"A raiva em animais pode ser prevenida com:", alt:["Vacinação anual de pets","Isolamento em mata","Comer ração cara","Banho diário"], c:0, e:"Campanhas de vacinação animal são eficazes."},
  {id:87, s:2, d:'d', q:"A chikungunya veio originalmente de:", alt:["Ásia/África","Europa","EUA","Brasil"], c:0, e:"Introduzida nas Américas por viagem internacional."},
  
  // ETAPA 3 (Bacterianas + Saneamento) - 38 questões
  {id:88, s:3, d:'f', q:"Leptospirose é transmitida por:", alt:["Urina de rato","Picada de mosquito","Ar condicionado","Comida queimada"], c:0, e:"Contato com água/lama contaminada por urina de roedores."},
  {id:89, s:3, d:'f', q:"Cólera causa principalmente:", alt:["Tosse","Diarreia aquosa intensa","Dor de cabeça","Manchas"], c:1, e:"Perda rápida de água/eletrólitos. Risco de desidratação."},
  {id:90, s:3, d:'f', q:"Tuberculose afeta principalmente:", alt:["Fígado","Pulmões","Coração","Pele"], c:1, e:"Bacilo de Koch (Mycobacterium tuberculosis)."},
  {id:91, s:3, d:'f', q:"Tétano entra no corpo por:", alt:["Inalação","Ferimentos contaminados","Picada de mosquito","Água potável"], c:1, e:"Esporos no solo/objetos entram em cortes profundos."},
  {id:92, s:3, d:'f', q:"Hanseníase é causada por:", alt:["Vírus","Bactéria (M. leprae)","Fungo","Protozoário"], c:1, e:"Doença negligenciada, tem tratamento gratuito pelo SUS."},
  {id:93, s:3, d:'f', q:"Saneamento básico inclui:", alt:["Só lixo","Água, esgoto e drenagem","Só hospitais","Vacinas"], c:1, e:"Infraestrutura que previne múltiplas doenças."},
  {id:94, s:3, d:'m', q:"Enchentes aumentam risco de:", alt:["Gripe","Leptospirose","Catapora","Zika"], c:1, e:"Alagamento mistura esgoto e urina de ratos."},
  {id:95, s:3, d:'m', q:"Cólera se previne com:", alt:["Higiene de alimentos/água","Vacina BCG","Isolamento social","Antibiótico preventivo"], c:0, e:"Cloração, cozimento, lavar mãos/vegetais."},
  {id:96, s:3, d:'m', q:"A vacina BCG protege contra:", alt:["Tétano","Tuberculose","Dengue","Cólera"], c:1, e:"Aplicada no braço, deixa cicatriz característica."},
  {id:97, s:3, d:'m', q:"Tétano causa:", alt:["Diarreia","Rigidez muscular e espasmos","Tosse","Febre baixa"], c:1, e:"Toxina tetanospasmina bloqueia inibição neural."},
  {id:98, s:3, d:'m', q:"Hanseníase se transmite por:", alt:["Contato prolongado/inalação de secreções respiratórias","Picada","Água","Sexo"], c:0, e:"Incubação longa. 90% são naturalmente resistentes."},
  {id:99, s:3, d:'m', q:"Saneamento precário favorece:", alt:["Doenças crônicas","Doenças de veiculação hídrica","Câncer","Alergias"], c:1, e:"Cólera, hepatite A, diarreias, parasitoses."},
  {id:100, s:3, d:'m', q:"Água tratada passa por:", alt:["Fervura em casa","Cloração e filtração","Nada","Apenas fervura solar"], c:1, e:"Processos de ETA garantem segurança microbiológica."},
  {id:101, s:3, d:'m', q:"Esgoto sem tratamento contamina:", alt:["Solo e mananciais","Apenas ar","Rochas","Nuvens"], c:0, e:"Retorna ao ciclo da água carregando patógenos."},
  {id:102, s:3, d:'m', q:"Lixo a céu aberto atrai:", alt:["Vacas","Ratos e vetores","Pássaros raros","Peixes"], c:1, e:"Aumenta risco de leptospirose e doenças por vetores."},
  {id:103, s:3, d:'m', q:"Pneumonia bacteriana é tratada com:", alt:["Antibiótico","Vacina","Soro","Antifúngico"], c:0, e:"Prescrição médica conforme agente."},
  {id:104, s:3, d:'m', q:"Fossa séptica evita:", alt:["Doenças aéreas","Contaminação do lençol freático","Alergias","Ruído"], c:1, e:"Trata dejetos onde não há rede de esgoto."},
  {id:105, s:3, d:'m', q:"Higienizar alimentos com hipoclorito:", alt:["É inútil","Elimina bactérias/vírus","Mancha tudo","Causa câncer"], c:1, e:"Cloro ativo mata patógenos superficiais."},
  {id:106, s:3, d:'m', q:"A bactéria da cólera é:", alt:["Vibrio cholerae","Bacilo de Koch","Treponema","Staphylococcus"], c:0, e:"Vibrio cholerae, causador de epidemias históricas."},
  {id:107, s:3, d:'m', q:"O tétano neonatal ocorre por:", alt:["Corte do cordão umbilical com instrumento sujo","Picada de mosquito","Ar condicionado","Leite materno"], c:0, e:"Prática insegura. Previna com parto hospitalar/vacina materna."},
  {id:108, s:3, d:'m', q:"Hanseníase tem cura?", alt:["Não","Sim, com poliquimioterapia gratuita","Só com cirurgia","Só com repouso"], c:1, e:"Tratamento longo, mas eficaz. Isolamento desnecessário."},
  {id:109, s:3, d:'m', q:"A diarreia por bactéria pode matar por:", alt:["Desidratação","Só dor","Febre","Tosse"], c:0, e:"Perda de água/sais. Soro de reidratação oral salva."},
  {id:110, s:3, d:'m', q:"Saneamento básico é considerado:", alt:["Direito humano","Luxo","Opção","Só para cidades grandes"], c:0, e:"Fundamental para saúde pública e dignidade."},
  {id:111, s:3, d:'d', q:"A leptospirose entra no corpo pela:", alt:["Pele/mucosa em contato com água contaminada","Inalação de ar seco","Picada","Comida crua"], c:0, e:"Lesões microscópicas ou conjuntiva facilitam entrada."},
  {id:112, s:3, d:'d', q:"A tuberculose é de notificação:", alt:["Opcional","Compulsória","Só em hospitais","Só para médicos"], c:1, e:"Vigilância epidemiológica ativa o controle."},
  {id:113, s:3, d:'d', q:"O soro antitetânico é dado quando:", alt:["Carteira está em dia","Ferimento de risco + vacinação incerta/defasada","Para gripe","No cólera"], c:1, e:"Passiva + ativa (vacina) simultâneas em casos graves."},
  {id:114, s:3, d:'d', q:"A resistência bacteriana surge por:", alt:["Uso indevido/excesso de antibióticos","Vacinação","Higiene","Saneamento"], c:0, e:"Seleção natural de cepas resistentes. Cuidado no uso!"},
  {id:115, s:3, d:'d', q:"Falta de rede de esgoto aumenta:", alt:["Índice pluviométrico","Carga de patógenos ambientais","Ruído urbano","Trânsito"], c:1, e:"Excrementos humanos no ambiente = risco sanitário."},
  {id:116, s:3, d:'d', q:"Hanseníase ataca:", alt:["Fígado","Pele e nervos periféricos","Pulmões","Rins"], c:1, e:"Lesões cutâneas, perda de sensibilidade, deformidades."},
  {id:117, s:3, d:'d', q:"A bactéria do tétano vive no:", alt:["Ar puro","Solo e intestino animal","Água doce","Sangue"], c:0, e:"Forma esporulada resistente no ambiente."},
  {id:118, s:3, d:'d', q:"Investir R$1 em saneamento economiza ~R$9 em saúde. Por quê?", alt:["Saneamento é caro","Previne custos de internação e perda de produtividade","Não economiza","Só melhora estética"], c:1, e:"Prevenção é sempre mais barata que tratamento de crises."},
  {id:119, s:3, d:'d', q:"A transmissão da hanseníase é:", alt:["Só por toque rápido","Contato próximo e prolongado","Só sexual","Aérea rápida"], c:0, e:"Exposição repetida necessária. 95% imunes naturalmente."},
  {id:120, s:3, d:'d', q:"A cólera é mais comum em:", alt:["Locais com água potável","Áreas de desastre/saneamento precário","Montanhas geladas","Desertos"], c:1, e:"Enchentes, conflitos, falta de infraestrutura."},
  {id:121, s:3, d:'d', q:"A tuberculose tem tratamento com:", alt:["Antibióticos por meses","Vacina anual","Soro","Cirurgia"], c:0, e:"Esquema RIPE por 6 meses. Adesão evita resistência."},
  {id:122, s:3, d:'d', q:"O controle de ratos previne:", alt:["Dengue","Leptospirose","Gripe","Malária"], c:1, e:"Rato = reservatório da bactéria."},
  {id:123, s:3, d:'d', q:"Falta de água encanada força uso de:", alt:["Poços contaminados ou caminhões-pipa","Só gelo","Só refrigerante","Nada"], c:0, e:"Risco de contaminação se fonte não for monitorada."},
  {id:124, s:3, d:'d', q:"Saneamento é dever do:", alt:["Estado e sociedade","Só do cidadão","Só de empresas","Ninguém"], c:0, e:"Políticas públicas + comportamento comunitário."},
  {id:125, s:3, d:'f', q:"Qual bactéria causa tétano?", alt:["Clostridium tetani","Mycobacterium","Vibrio","Salmonella"], c:0, e:"Bacilo Gram-positivo, produtor de toxina neural."},
  
  // ETAPA 4 (Revisão Final + Interpretação) - 35 questões
  {id:126, s:4, d:'f', q:"Antibiótico cura gripe?", alt:["Sim","Não","Às vezes","Só em crianças"], c:1, e:"Gripe é viral. Antibióticos são inúteis e prejudiciais aqui."},
  {id:127, s:4, d:'f', q:"Macacos transmitem febre amarela?", alt:["Sim","Não","Só bugios","Só saguis"], c:1, e:"São vítimas/sentinels. Não infectam humanos."},
  {id:128, s:4, d:'f', q:"Lavar mãos previne:", alt:["Só gripe","Várias doenças","Nada","Apenas alergias"], c:1, e:"Remove patógenos de contato. Eficaz e barato."},
  {id:129, s:4, d:'f', q:"Água parada favorece:", alt:["Tuberculose","Aedes","Hanseníase","Cólera"], c:1, e:"Criadouro de mosquitos vetores."},
  {id:130, s:4, d:'f', q:"Fake news geralmente:", alt:["Cita fontes","Usa sensacionalismo","É técnica","É lenta"], c:1, e:"Medo, urgência e falta de autoria."},
  {id:131, s:4, d:'m', q:"Se uma região tem dengue alta e baixa cólera, o problema principal é:", alt:["Só falta água","Vetor urbano + saneamento relativo","Só clima","Só pobreza"], c:1, e:"Dengue = água parada domiciliar. Cólera = água de ingestão contaminada."},
  {id:132, s:4, d:'m', q:"Vacinar animais previne:", alt:["Dengue","Raiva","Cólera","Malária"], c:1, e:"Quebra ciclo zoonótico."},
  {id:133, s:4, d:'m', q:"Qual medida NÃO previne leptospirose?", alt:["Eliminar água parada","Usar calçados em enchentes","Controle de ratos","Saneamento"], c:0, e:"Água parada atrai Aedes, não rato. Lepto = lama/urina."},
  {id:134, s:4, d:'m', q:"O que diferencia epidemia de endemia?", alt:["Duração/padrão","Agente","Tratamento","Idade"], c:0, e:"Surto vs constante."},
  {id:135, s:4, d:'m', q:"Soro é indicado quando:", alt:["Precisa de proteção futura","Já há exposição/agente no corpo","Para gripe leve","Para vacinar"], c:1, e:"Imunização passiva emergencial."},
  {id:136, s:4, d:'m', q:"Por que macacos morrem de febre amarela?", alt:["São imunes","São sensíveis, como humanos","São vetores","Comem mosquito"], c:1, e:"Indicadores de circulação viral na mata."},
  {id:137, s:4, d:'m', q:"Qual afirmação sobre saneamento é correta?", alt:["Só evita bactérias","Evita múltiplas doenças e melhora economia","Só em cidades","Não afeta saúde"], c:1, e:"Base da saúde pública."},
  {id:138, s:4, d:'m', q:"Aedes aegypti NÃO transmite:", alt:["Dengue","Zika","Malária","Chikungunya"], c:2, e:"Malária = Anopheles."},
  {id:139, s:4, d:'m', q:"Higienizar com vinagre:", alt:["É tão bom quanto cloro","Menos eficaz contra patógenos","Causa intoxicação","É proibido"], c:1, e:"Vinagre limpa, mas não desinfeta como cloro ativo."},
  {id:140, s:4, d:'m', q:"Vacina tríplice viral NÃO protege contra:", alt:["Caxumba","Sarampo","Rubéola","Dengue"], c:3, e:"Dengue tem vacina específica (quando indicada)."},
  {id:141, s:4, d:'d', q:"Se um bairro tem água tratada mas esgoto a céu aberto, espera-se:", alt:["Zero doenças","Diarreias e parasitoses","Dengue","Gripe"], c:1, e:"Ciclo fecal-oral ativo por saneamento incompleto."},
  {id:142, s:4, d:'d', q:"Por que a vacinação é coletiva?", alt:["Só protege o vacinado","Reduz circulação, protegendo todos","Gera lucro","É obrigatória por lei"], c:1, e:"Imunidade de rebanho é conceito populacional."},
  {id:143, s:4, d:'d', q:"Qual cenário indica necessidade de lockdown?", alt:["Poucos casos","Colapso iminente de UTIs","Férias","Chuva"], c:1, e:"Medida extrema para frear transmissão e salvar sistema."},
  {id:144, s:4, d:'d', q:"Aedes aegypti se adapta a:", alt:["Só florestas","Urbano e doméstico","Apenas frio","Apenas calor extremo"], c:1, e:"Peridomicílio: pneus, vasos, calhas."},
  {id:145, s:4, d:'d', q:"Fake news sobre saúde prejudica:", alt:["Só o autor","A adesão a campanhas e a saúde pública","Nada","A economia"], c:1, e:"Desinformação custa vidas e recursos."},
  {id:146, s:4, d:'d', q:"Qual combinação previne cólera E leptospirose?", alt:["Só vacina","Saneamento + higiene + controle de ratos/enchentes","Só máscara","Só ar condicionado"], c:1, e:"Medidas estruturais e comportamentais integradas."},
  {id:147, s:4, d:'d', q:"O que é 'imunidade de rebanho'?", alt:["Vacas vacinadas","Proteção indireta quando maioria é imune","Doença de gado","Vacina cara"], c:1, e:"Conceito epidemiológico crucial."},
  {id:148, s:4, d:'d', q:"Se um aluno diz 'antibiótico cura dengue', ele:", alt:["Está certo","Confunde agente causal","Só para adultos","Só em hospitais"], c:1, e:"Dengue é viral. Antibiótico não age contra vírus."},
  {id:149, s:4, d:'d', q:"Qual é a melhor forma de evitar fake news?", alt:["Compartilhar sem ler","Verificar fonte oficial/consenso","Acreditar em áudios","Ignorar ciência"], c:1, e:"Checagem de fatos e fontes confiáveis."},
  {id:150, s:4, d:'d', q:"O saneamento básico é a base para:", alt:["Doenças","Prevenção primária e desenvolvimento","Poluição","Isolamento"], c:1, e:"Determinante social de saúde."}
],
  matematica: [],
  portugues: []
};